/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStaticPorts implements StaticPortInterface
type FakeStaticPorts struct {
	Fake *FakeKubeovnV1
}

var staticportsResource = schema.GroupVersionResource{Group: "kubeovn.io", Version: "v1", Resource: "security-groups"}

var staticportsKind = schema.GroupVersionKind{Group: "kubeovn.io", Version: "v1", Kind: "StaticPort"}

// Get takes name of the staticPort, and returns the corresponding staticPort object, and an error if there is any.
func (c *FakeStaticPorts) Get(ctx context.Context, name string, options v1.GetOptions) (result *kubeovnv1.StaticPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(staticportsResource, name), &kubeovnv1.StaticPort{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kubeovnv1.StaticPort), err
}

// List takes label and field selectors, and returns the list of StaticPorts that match those selectors.
func (c *FakeStaticPorts) List(ctx context.Context, opts v1.ListOptions) (result *kubeovnv1.StaticPortList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(staticportsResource, staticportsKind, opts), &kubeovnv1.StaticPortList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kubeovnv1.StaticPortList{ListMeta: obj.(*kubeovnv1.StaticPortList).ListMeta}
	for _, item := range obj.(*kubeovnv1.StaticPortList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested staticPorts.
func (c *FakeStaticPorts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(staticportsResource, opts))
}

// Create takes the representation of a staticPort and creates it.  Returns the server's representation of the staticPort, and an error, if there is any.
func (c *FakeStaticPorts) Create(ctx context.Context, staticPort *kubeovnv1.StaticPort, opts v1.CreateOptions) (result *kubeovnv1.StaticPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(staticportsResource, staticPort), &kubeovnv1.StaticPort{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kubeovnv1.StaticPort), err
}

// Update takes the representation of a staticPort and updates it. Returns the server's representation of the staticPort, and an error, if there is any.
func (c *FakeStaticPorts) Update(ctx context.Context, staticPort *kubeovnv1.StaticPort, opts v1.UpdateOptions) (result *kubeovnv1.StaticPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(staticportsResource, staticPort), &kubeovnv1.StaticPort{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kubeovnv1.StaticPort), err
}

// Delete takes name of the staticPort and deletes it. Returns an error if one occurs.
func (c *FakeStaticPorts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(staticportsResource, name), &kubeovnv1.StaticPort{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStaticPorts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(staticportsResource, listOpts)

	_, err := c.Fake.Invokes(action, &kubeovnv1.StaticPortList{})
	return err
}

// Patch applies the patch and returns the patched staticPort.
func (c *FakeStaticPorts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubeovnv1.StaticPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(staticportsResource, name, pt, data, subresources...), &kubeovnv1.StaticPort{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kubeovnv1.StaticPort), err
}
